// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEt6u09KtXAZbAMZ6YsR76ewm8RC08WMg',
    appId: '1:217666245776:web:d14e3c85ea0949e5df3415',
    messagingSenderId: '217666245776',
    projectId: 'cvapp-75fa0',
    authDomain: 'cvapp-75fa0.firebaseapp.com',
    storageBucket: 'cvapp-75fa0.appspot.com',
    measurementId: 'G-E1G1BKX0ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2343enSmAsKt6ErHP1WazBiOjkuIdkhc',
    appId: '1:217666245776:android:5307fac701973403df3415',
    messagingSenderId: '217666245776',
    projectId: 'cvapp-75fa0',
    storageBucket: 'cvapp-75fa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACnMdXe6bun6Uw6RkntZk_cwgOK3fyeq0',
    appId: '1:217666245776:ios:656b1dba429304ffdf3415',
    messagingSenderId: '217666245776',
    projectId: 'cvapp-75fa0',
    storageBucket: 'cvapp-75fa0.appspot.com',
    iosBundleId: 'com.cv.app.cvapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACnMdXe6bun6Uw6RkntZk_cwgOK3fyeq0',
    appId: '1:217666245776:ios:f71902dfa09d0199df3415',
    messagingSenderId: '217666245776',
    projectId: 'cvapp-75fa0',
    storageBucket: 'cvapp-75fa0.appspot.com',
    iosBundleId: 'com.cv.app.cvapp.RunnerTests',
  );
}
